services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.fpm

    container_name: tuneOps_app

    volumes:
      - ./:/app

    working_dir: /app

    ports:
      - '8000:80'

    depends_on:
      - redis
      - mariadb

    command: php-fpm

  nginx:
    image: nginx:alpine
    container_name: tuneOps_nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    working_dir: /app

  discord-bot:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: tuneOps_discord_bot

    volumes:
      - ./:/app
      - discord_bot_node_modules:/app/node_modules

    working_dir: /app

    command: bash -lc "npm install && npm run bot:discord"

    depends_on:
      - app
      - redis

  redis:
    image: redis:7

    container_name: tuneOps_redis

    ports:
      - '6379:6379'

  mariadb:
    image: mariadb:11

    container_name: tuneOps_bot_db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tuneOps_bot
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

    ports:
      - '3306:3306'

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  discord_bot_node_modules:
