services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: tuneOps_app

    volumes:
      - ./:/app

    working_dir: /app

    stdin_open: true
    tty: true

    ports:
      - '8000:8000'

    depends_on:
      - redis
      - mariadb

  redis:
    image: redis:7

    container_name: tuneOps_redis

    ports:
      - '6379:6379'

  mariadb:
    image: mariadb:11

    container_name: music_bot_db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_bot
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

    ports:
      - '3306:3306'

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
